# Generated by Django 3.2.4 on 2021-06-06 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cranes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craneType', models.CharField(max_length=100)),
                ('loadCapacity', models.IntegerField()),
                ('registerNumber', models.IntegerField(unique=True)),
                ('factoryNumber', models.IntegerField(unique=True)),
                ('inventorizationNumber', models.IntegerField(unique=True)),
                ('factoryManufacturer', models.CharField(max_length=100, unique=True)),
                ('examinationPeriod', models.DateTimeField()),
                ('workMode', models.CharField(max_length=50)),
                ('installationPlace', models.CharField(max_length=120)),
                ('technicalMaintenanceFirst', models.CharField(max_length=100)),
                ('technicalMaintenanceSecond', models.CharField(max_length=100)),
                ('inspection', models.CharField(max_length=100)),
                ('personResponsibleToFixedState', models.CharField(max_length=100)),
                ('personResponsibleForSupervision', models.CharField(max_length=100)),
                ('metalInspection', models.CharField(max_length=100)),
                ('mechanicalControl', models.CharField(max_length=100)),
                ('electricalParts', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
