# Generated by Django 3.2.4 on 2021-07-05 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPeriodTechPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicalPassportdownloadUrl', models.FileField(upload_to='')),
                ('examinationPeriodDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FirstTechnicalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodOfFirstTMfrom', models.DateTimeField()),
                ('periodOfFirstTMto', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodInspectionfrom', models.DateTimeField()),
                ('periodInspectionto', models.DateTimeField()),
                ('inspection', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonResponsibleForSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personImage', models.ImageField(upload_to='')),
                ('employeePost', models.CharField(max_length=100)),
                ('orderNumber', models.IntegerField(unique=True)),
                ('employeeFirstName', models.CharField(max_length=100)),
                ('employeeSecondName', models.CharField(max_length=100)),
                ('employeePatronymic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonResponsibleToFixedState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personImage', models.ImageField(upload_to='')),
                ('employeePost', models.CharField(max_length=100)),
                ('orderNumber', models.IntegerField(unique=True)),
                ('employeeFirstName', models.CharField(max_length=100)),
                ('employeeSecondName', models.CharField(max_length=100)),
                ('employeePatronymic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecondTechnicalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodOfSecondTMfrom', models.DateTimeField()),
                ('periodOfSecondTMto', models.DateTimeField()),
                ('defectsStatement', models.CharField(max_length=200)),
                ('materialsStatement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cranes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craneType', models.CharField(max_length=100)),
                ('loadCapacity', models.IntegerField()),
                ('registerNumber', models.IntegerField(unique=True)),
                ('factoryNumber', models.IntegerField(unique=True)),
                ('inventorizationNumber', models.IntegerField(unique=True)),
                ('factoryManufacturer', models.CharField(max_length=100, unique=True)),
                ('workMode', models.CharField(max_length=50)),
                ('installationPlace', models.CharField(max_length=120)),
                ('metalInspection', models.CharField(max_length=100)),
                ('mechanicalControl', models.CharField(max_length=100)),
                ('electricalParts', models.CharField(max_length=100)),
                ('examinationPeriod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to='cranes.examinationperiodtechpassport')),
                ('inspection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to='cranes.inspection')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to=settings.AUTH_USER_MODEL)),
                ('personResponsibleForSupervision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to='cranes.personresponsibleforsupervision')),
                ('personResponsibleToFixedState', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to='cranes.personresponsibletofixedstate')),
                ('technicalMaintenanceFirst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to='cranes.firsttechnicalmaintenance')),
                ('technicalMaintenanceSecond', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to='cranes.secondtechnicalmaintenance')),
            ],
        ),
    ]
