# Generated by Django 3.2.4 on 2021-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cranes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cranes',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examinationperiodtechpassport',
            name='examinationPeriodDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='firsttechnicalmaintenance',
            name='periodOfFirstTMfrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='firsttechnicalmaintenance',
            name='periodOfFirstTMto',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='periodInspectionfrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='periodInspectionto',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='secondtechnicalmaintenance',
            name='periodOfSecondTMfrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='secondtechnicalmaintenance',
            name='periodOfSecondTMto',
            field=models.DateTimeField(),
        ),
    ]
