# Generated by Django 3.2.4 on 2021-06-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cranes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cranes',
            name='craneType',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='electricalParts',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='factoryManufacturer',
            field=models.CharField(max_length=360, unique=True),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='factoryNumber',
            field=models.IntegerField(max_length=360, unique=True),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='inspection',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='installationPlace',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='inventorizationNumber',
            field=models.IntegerField(max_length=360, unique=True),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='loadCapacity',
            field=models.IntegerField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='mechanicalControl',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='metalInspection',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='personResponsibleForSupervision',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='personResponsibleToFixedState',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='registerNumber',
            field=models.IntegerField(max_length=360, unique=True),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='technicalMaintenanceFirst',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='technicalMaintenanceSecond',
            field=models.CharField(max_length=360),
        ),
    ]
