# Generated by Django 3.2.4 on 2021-08-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cranes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationperiodtechpassport',
            name='technicalPassportdownloadUrl',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personresponsibleforsupervision',
            name='personImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='personresponsibletofixedstate',
            name='personImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
