# Generated by Django 3.2.4 on 2021-06-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cranes', '0002_auto_20210629_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cranes',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='cranes',
            name='personResponsibleForSupervision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to='cranes.personresponsibleforsupervision'),
        ),
        migrations.AlterField(
            model_name='cranes',
            name='personResponsibleToFixedState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cranes', to='cranes.personresponsibletofixedstate'),
        ),
    ]
