# Generated by Django 3.2.4 on 2021-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cranes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craneType', models.CharField(max_length=100)),
                ('loadCapacity', models.IntegerField(max_length=100)),
                ('registerNumber', models.IntegerField(max_length=100, unique=True)),
                ('factoryNumber', models.IntegerField(max_length=100, unique=True)),
                ('inventorizationNumber', models.IntegerField(max_length=100, unique=True)),
                ('factoryManufacturer', models.CharField(max_length=100, unique=True)),
                ('examinationPeriod', models.DateTimeField()),
                ('workMode', models.CharField(max_length=50)),
                ('installationPlace', models.CharField(max_length=120)),
                ('technicalMaintenanceFirst', models.CharField(max_length=100)),
                ('technicalMaintenanceSecond', models.CharField(max_length=100)),
                ('inspection', models.CharField(max_length=100)),
                ('personResponsibleToFixedState', models.CharField(max_length=100)),
                ('personResponsibleForSupervision', models.CharField(max_length=100)),
                ('metalInspection', models.CharField(max_length=100)),
                ('mechanicalControl', models.CharField(max_length=100)),
                ('electricalParts', models.CharField(max_length=100)),
            ],
        ),
    ]
